### PR TITLE
Add edit task support

### PR DESCRIPTION
**Pull request by jaredkaczynski**
- Creates CreateDialog when edit button clicked
- Loads CreateDialog with task data and disables quantity
- On edit task clicked, update task data, refresh UI labels, delete task from JSON, re-add task to JSON

### CODE REVIEW

**Comment by raman325** [comment]
Thanks for submitting this! I rebased master on both this and your other PR, but I noticed that edit doesn't load the profile list correctly. Just an FYI!

**Comment by jaredkaczynski** [comment]
> Thanks for submitting this! I rebased master on both this and your other PR, but I noticed that edit doesn't load the profile list correctly. Just an FYI!

What does it load on your end, can you be more descriptive? Does the proxies load properly? Are the proxies and profiles loaded properly in the original Create Task menu? The fields are pulled directly from this menu and added to the edit task window.

**Comment by raman325** [comment]
sorry, to be more precise, when I open the "profile" drop down there is nothing but "Profile". I don't have any proxies set but when I click the drop down for that I see "Proxy List" and "None" so I think that one is loading correctly

**Comment by natewong1313** [comment]
Thanks!

**Pull request merged**
